launch: #起動パラメータ
  ros__parameters:
    odrive : true
    socketcan : true

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    # 並進  速度[m/s],加速度[m/s^2]
    linear_max:
      vel : 5.5
      acc: 5.0
    # 舵角  位置[deg]
    steering_max :
      pos : 7.0

    tread : 0.6
    wheelbase : 0.8

chassis_driver_node:
  ros__parameters:
    interval_ms : 2
    wheel_radius : 0.124
    reduction_ratio : 1.0
    reverse_left_flag : false
    reverse_right_flag : false
    use_velocity_body : true
    caster:
      max_count : 16384
      gear_ratio : 0.59090909090909
      wheel_radius : 0.12 # [m]
      reel_radius : 0.02 # [m]
      steering_radius : 0.032 # [m]
      preload_length : 0.03 # [m]
      preload_gain : 0.1
    drive_pid:
      p_gain : 3.0
      i_gain : 0.0
      d_gain : 0.1

socketcan_interface_node:
  ros__parameters:
    if_name : "can_main"
